/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import Controle.Cidade;
import DAO.CiidadeDao;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuário
 */
public class FormCidade extends javax.swing.JFrame {

    /**
     * Creates new form FormCidade
     */
    public FormCidade() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        CmbEstado = new javax.swing.JComboBox<>();
        btSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaCidade = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        btExcluir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Cidade");

        jLabel3.setText("Estado");

        CmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceara", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia\tP", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));
        CmbEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbEstadoItemStateChanged(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        TabelaCidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Cidade", "Estado"
            }
        ));
        TabelaCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaCidadeMouseClicked(evt);
            }
        });
        TabelaCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TabelaCidadeKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaCidade);

        jTextField1.setText("jTextField1");

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSair.setText("Sair");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(CmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSalvar)
                        .addGap(132, 132, 132)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSair))
                    .addComponent(jScrollPane1)
                    .addComponent(jTextField1))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btExcluir)
                    .addComponent(btSair))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:

        if (txtCodigo.getText().equals("")) {
            // salvar os registro no banco de dados
            SalvarCidade();

        } else {
            // fazer atualização dos registros
            AtualizarCidade();
        }
        preencherTabela();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        ExcluirCidade();
        preencherTabela();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void TabelaCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaCidadeKeyPressed
        // TODO add your handling code here:
       
        // Chamando o método para fazer o preenchinto dos dados
        preencherInformacao ();
    }//GEN-LAST:event_TabelaCidadeKeyPressed

    private void TabelaCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaCidadeMouseClicked
        // TODO add your handling code here:
         // Chamando o método para fazer o preenchinto dos dados
        preencherInformacao ();
    }//GEN-LAST:event_TabelaCidadeMouseClicked

    private void CmbEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbEstadoItemStateChanged
        // TODO add your handling code here:
        // preencherInformacao ();
    }//GEN-LAST:event_CmbEstadoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCidade().setVisible(true);
            }
        });
    }

    // Método Salvar
    private boolean SalvarCidade() {
        // Classe de Controlle  get  e set 
        Cidade cidade = new Cidade();
        cidade.setNomeCidade(txtCidade.getText());
        cidade.setEstado(CmbEstado.getSelectedItem().toString());
        // Classe de DAO  método de  salvar
        CiidadeDao dao = new CiidadeDao();
        dao.Salvar(cidade);

        return true;
    }

    // Método atualizar
    private boolean AtualizarCidade() {
        // Classe de Controlle  get  e set 
        Cidade cidade = new Cidade();
        cidade.setCodigoCidade(Integer.parseInt(txtCodigo.getText()));
        cidade.setNomeCidade(txtCidade.getText());
        cidade.setEstado(CmbEstado.getSelectedItem().toString());
        // Classe de DAO  método de  salvar

        CiidadeDao dao = new CiidadeDao();
        dao.atualizar(cidade);
        return true;
    }
    // Método de excluir os dados de acordo com código selecionado

    private boolean ExcluirCidade() {
        // Classe que contém os métodos get e set
        Cidade cidade = new Cidade();
        cidade.setCodigoCidade(Integer.parseInt(txtCodigo.getText()));
        // Classe que contém o método de exclusão 
        CiidadeDao dao = new CiidadeDao();
        dao.Excluir(cidade);

        return true;

    }

    // Método para preencher Tabela
    private void preencherTabela() {
        DefaultTableModel modelo = (DefaultTableModel) TabelaCidade.getModel();
        modelo.setNumRows(0);

        CiidadeDao listaCidade = new CiidadeDao();
        for (Cidade p : listaCidade.listarCidade()) {
            modelo.addRow(new Object[]{
                p.getCodigoCidade(),
                p.getNomeCidade(),
                p.getEstado()

            }
            );
        }
    }
    // Método Preencher tabela para realizar exclusão e atualização de dados
    
    public  boolean preencherInformacao (){
        int row = TabelaCidade.getSelectedRow();
        if (TabelaCidade.getSelectedRow()!=-1){
            txtCodigo.setText(String.valueOf(TabelaCidade.getValueAt(row,0)));
            txtCidade.setText(String.valueOf(TabelaCidade.getValueAt(row,1)));
            CmbEstado.addItem(String.valueOf(TabelaCidade.getModel().getValueAt(TabelaCidade.getSelectedRow(),2)));
       
        }
        return true;
       
    }
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbEstado;
    private javax.swing.JTable TabelaCidade;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
