/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import Controle.Cidade;
import Controle.Professor;
import DAO.CiidadeDao;
import DAO.ProfessorDao;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hélio
 */
public class FormProf extends javax.swing.JFrame {
    Vector<Cidade> cidades;

    /**
     * Creates new form FormProf
     */
    public FormProf() {
        initComponents();
        CarregarTabela();
        ProfessorDao profDao = new ProfessorDao();
        cidades = profDao.CarregarCidade();
        combCid.setModel(new DefaultComboBoxModel(cidades));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jEnd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        combCid = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jForm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProf = new javax.swing.JTable();
        jSave = new javax.swing.JButton();
        jDel = new javax.swing.JButton();
        jExit = new javax.swing.JButton();
        bAtu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Nome");

        jLabel3.setText("Endereço");

        jEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEndActionPerformed(evt);
            }
        });

        jLabel4.setText("Cidade");

        combCid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Telefone");

        jLabel6.setText("Formação");

        tabelaProf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Endereço", "Cidade", "Telefone", "Formação"
            }
        ));
        jScrollPane1.setViewportView(tabelaProf);

        jSave.setText("Salvar");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        jDel.setText("Excluir");
        jDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDelActionPerformed(evt);
            }
        });

        jExit.setText("Sair");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        bAtu.setText("Atualizar");
        bAtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSave)
                        .addGap(96, 96, 96)
                        .addComponent(bAtu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDel)
                        .addGap(104, 104, 104)
                        .addComponent(jExit))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jcod, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(combCid, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jForm)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combCid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSave)
                    .addComponent(jDel)
                    .addComponent(jExit)
                    .addComponent(bAtu))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEndActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
        // TODO add your handling code here:
        SalvarProfessor();
        CarregarTabela();
    }//GEN-LAST:event_jSaveActionPerformed

    private void jDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDelActionPerformed
        // TODO add your handling code here:
        ExcluirProfessor();
        CarregarTabela();
    }//GEN-LAST:event_jDelActionPerformed

    private void bAtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtuActionPerformed
        // TODO add your handling code here:
        AtualizarProfessor();
        CarregarTabela();
    }//GEN-LAST:event_bAtuActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProf().setVisible(true);
            }
        });
    }
    
    //Método salvar 
    public boolean SalvarProfessor() {

        Professor professor = new Professor();
        professor.setNome(jNome.getText());
        professor.setEndereco(jEnd.getText());
        professor.setCodigoCidade(cidades.get(combCid.getSelectedIndex()));
        professor.setTelefone(jTel.getText());
        professor.setFormacao(jForm.getText());
        ProfessorDao profDao = new ProfessorDao();
        profDao.SalvarProfessor(professor);

        return true;

    }

    // Método Atualizar 
    public boolean AtualizarProfessor() {

        Professor professor = new Professor();

        professor.setCodigoProf(Integer.parseInt(jcod.getText()));
        professor.setNome(jNome.getText());
        professor.setEndereco(jEnd.getText());
        professor.setCodigoCidade(cidades.get(combCid.getSelectedIndex()));
        professor.setTelefone(jTel.getText());
        professor.setFormacao(jForm.getText());
        ProfessorDao profDao = new ProfessorDao();
        profDao.AtualizarProfessor(professor);

        return true;

    }
    
    // Método de excluir os dados de acordo com código selecionado

    private boolean ExcluirProfessor() {
        // Classe que contém os métodos get e set
        Professor professor = new Professor();
        professor.setCodigoProf(Integer.parseInt(jcod.getText()));
        // Classe que contém o método excluir 
        ProfessorDao dao = new ProfessorDao();
        dao.Excluir(professor);

        return true;

    }

    //Método Carregar Tabela
    public void CarregarTabela() {

        Vector cabecalho;
        cabecalho = new Vector();
        cabecalho.add("Código");
        cabecalho.add("Nome");
        cabecalho.add("Endereço");
        cabecalho.add("Cidade");
        cabecalho.add("Telefone");
        cabecalho.add("Formação");

        ProfessorDao profDao = new ProfessorDao();
        tabelaProf.setModel(new DefaultTableModel(profDao.CarregarProfTabela(), cabecalho));
    }
    
    
   
   //Método para a devolução de valores
    public  boolean preencherjTextCombox (){
        int x = Integer.parseInt(tabelaProf.getModel().getValueAt(tabelaProf.getSelectedRow(),0).toString());
        Professor prof = new Professor();
         ProfessorDao profDao =new ProfessorDao();
         prof=profDao.PesquisarCidade(x);
             
       combCid.getModel().setSelectedItem(prof.getCodigoCidade());
        
        jcod.setText(String.valueOf(prof.getCodigoProf()));
        jNome.setText(String.valueOf(prof.getNome()));
        jEnd.setText(String.valueOf(prof.getEndereco()));
        jTel.setText(String.valueOf(prof.getTelefone()));
        jForm.setText(String.valueOf(prof.getFormacao()));
        
        return  true;
        
    }
    
    // Método para preencher Tabela
    private void preencherTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaProf.getModel();
        modelo.setNumRows(0);

        ProfessorDao listProf = new ProfessorDao();
        for (Professor p : listProf.listarProfessor()) {
            modelo.addRow(new Object[]{
                p.getCodigoProf(),
                p.getNome(),
                p.getEndereco(),
                p.getCodigoCidade(),
                p.getTelefone(),
                p.getFormacao()

            }
            );
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtu;
    private javax.swing.JComboBox<String> combCid;
    private javax.swing.JButton jDel;
    private javax.swing.JTextField jEnd;
    private javax.swing.JButton jExit;
    private javax.swing.JTextField jForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNome;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTel;
    private javax.swing.JTextField jcod;
    private javax.swing.JTable tabelaProf;
    // End of variables declaration//GEN-END:variables
}
